# 📝 01_bronze_exploration

In [3]:
import duckdb
import pandas as pd
import numpy as np
from dotenv import load_dotenv
import os

load_dotenv()
motherduck_token = os.getenv("MOTHERDUCKTOKEN")

with duckdb.connect(f'md:?motherduck_token={motherduck_token}') as con:
    raw_movie_df = con.sql("SELECT * FROM imdb_analytics.bronze.raw_ranked_media_data;").df()

In [4]:
df = pd.DataFrame.from_dict(list(raw_movie_df["result"]))
df.head(3)

,rank,Series_Title,Released_Year,Poster_Link,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,1,The Shawshank Redemption,1994,https://m.media-amazon.com/images/M/MV5BMDFkYT...,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,2,The Godfather,1972,https://m.media-amazon.com/images/M/MV5BM2MyNj...,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,3,The Dark Knight,2008,https://m.media-amazon.com/images/M/MV5BMTMxNT...,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"

In [5]:
for column in ["Series_Title", "Certificate", "Genre"]:
    print(df[column].value_counts())
    print("\n")

Series_Title
Drishyam                    2
The Shawshank Redemption    1
Awakenings                  1
Tombstone                   1
The Sandlot                 1
                           ..
Guardians of the Galaxy     1
Blade Runner 2049           1
Her                         1
Bohemian Rhapsody           1
The 39 Steps                1
Name: count, Length: 999, dtype: int64


Certificate
U           234
A           197
UA          175
R           146
PG-13        43
PG           37
Passed       34
G            12
Approved     11
TV-PG         3
GP            2
TV-14         1
16            1
TV-MA         1
Unrated       1
U/A           1
Name: count, dtype: int64


Genre
Drama                        85
Drama, Romance               37
Comedy, Drama                35
Comedy, Drama, Romance       31
Action, Crime, Drama         30
                             ..
Adventure, Thriller           1
Animation, Action, Sci-Fi     1
Action, Crime, Comedy         1
Animation, Crime, Mystery     1
Adventure, Comedy, War        1
Name: count, Length: 202, dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   rank           1000 non-null   int64
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Poster_Link    1000 non-null   object
 4   Certificate    899 non-null    object
 5   Runtime        1000 non-null   object
 6   Genre          1000 non-null   object
 7   IMDB_Rating    1000 non-null   object
 8   Overview       1000 non-null   object
 9   Meta_score     843 non-null    object
 10  Director       1000 non-null   object
 11  Star1          1000 non-null   object
 12  Star2          1000 non-null   object
 13  Star3          1000 non-null   object
 14  Star4          1000 non-null   object
 15  No_of_Votes    1000 non-null   object
 16  Gross          831 non-null    object
dtypes: int64(1), object(16)
memory usage: 132.9+ KB

In [6]:
print("=====NULL COUNTS PER COLUMN=====")
df.isna().sum()

=====NULL COUNTS PER COLUMN=====

rank               0
Series_Title       0
Released_Year      0
Poster_Link        0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

In [6]:
df["Series_Title"][df["Series_Title"].duplicated()]

136    Drishyam
Name: Series_Title, dtype: object

In [8]:
df[df["Series_Title"] == "Drishyam"]

,rank,Series_Title,Released_Year,Poster_Link,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
87,88,Drishyam,2013,https://m.media-amazon.com/images/M/MV5BYmY3Mz...,U,160 min,"Crime, Drama, Thriller",8.3,A man goes to extreme lengths to save his fami...,None,Jeethu Joseph,Mohanlal,Meena,Asha Sharath,Ansiba,30722,None
136,137,Drishyam,2015,https://m.media-amazon.com/images/M/MV5BYmJhZm...,UA,163 min,"Crime, Drama, Mystery",8.2,Desperate measures are taken by a man who trie...,None,Nishikant Kamat,Ajay Devgn,Shriya Saran,Tabu,Rajat Kapoor,70367,"739,478"

In [7]:
df.head(3)

,rank,Series_Title,Released_Year,Poster_Link,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,1,The Shawshank Redemption,1994,https://m.media-amazon.com/images/M/MV5BMDFkYT...,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,2,The Godfather,1972,https://m.media-amazon.com/images/M/MV5BM2MyNj...,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,3,The Dark Knight,2008,https://m.media-amazon.com/images/M/MV5BMTMxNT...,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"

In [8]:
int(df["Runtime"].iloc[3].split(" ")[0])

202

In [9]:
number_list = df["Gross"].iloc[1].split(",")
string_number = ""
for number in number_list:
    string_number += f"{number}"
print("USD " + string_number)

USD 134966411

In [13]:
for value in list(df["Released_Year"]):
    print(value)

1994
1972
2008
1974
1957
2003
1994
1993
2010
1999
2001
1994
1966
2002
1999
1990
1980
1975
2020
2019
2020
2014
2002
2001
1998
1999
1997
1995
1991
1977
1962
1954
1946
2019
2014
2011
2006
2006
2002
2000
1998
1995
1994
1994
1991
1988
1988
1985
1968
1960
1942
1936
1931
2018
2017
2017
2016
2016
2018
2019
2018
2017
2012
2012
2009
2007
2008
2006
2003
2000
1997
1984
1981
1980
1979
1979
1971
1963
1964
1957
1957
1954
1950
1940
2019
2018
2018
2013
2012
2011
2010
2019
2005
2009
2004
2001
2000
2000
1999
1997
1997
1995
1995
1992
1987
1985
1986
1984
1983
1983
1981
1976
1973
1971
1968
1965
1962
1960
1959
1958
1952
1952
1948
1944
1941
1931
1927
1921
2019
2018
2018
2018
2017
2015
2017
2019
2015
2013
2013
2013
2012
2010
2012
2009
2011
2010
2009
2013
2007
2007
2006
2010
2005
2006
2005
2005
2004
2004
2004
2001
2000
1998
1997
1996
1995
1995
1994
1992
1989
1988
1988
1988
1985
1980
1979
1978
1976
1975
1975
1963
1962
1961
1961
1959
1957
1957
1955
1954
1953
1950
1950
1948
1942
1925
1924
2019
2016
2016
2016
2016
2014
2014
2017
2015
2014
2020
2014
2014
2012
2014
2014
2012
2016
2015
2012
2013
2013
2019
2015
2014
2012
2011
2013
2015
2008
2008
2011
2008
2009
2009
2010
2007
2007
2006
2004
2004
2004
2004
2003
2003
2001
2003
2003
2002
2000
2001
1997
2001
1999
1998
1998
1998
1998
2000
1996
1996
1995
1995
1995
1995
1994
1994
1993
1993
1993
1991
1989
1986
1986
1984
1984
1982
1982
1982
1982
1982
1980
1979
1978
1976
1976
1975
1975
1974
1973
1972
1972
1967
1967
1966
1966
1966
1962
1962
1962
1962
1962
1960
1960
1959
1959
1958
1957
1957
1957
1954
1953
1951
1949
1949
1948
1940
1940
1939
1939
1937
1934
1928
1928
1927
1926
1920
2018
2019
2016
2015
2015
2016
2016
2015
2016
2015
2013
2017
2019
2013
2013
2014
2014
2014
2017
2013
2018
2015
2012
2010
2010
2011
2016
2009
2009
2008
2010
2009
2008
2010
2007
2012
2007
2013
2006
2006
2007
2004
2005
2007
2004
2007
2006
2004
2003
2003
2014
2005
2003
2002
2003
2003
2004
2001
2003
2001
2001
1999
2000
1999
1997
1998
1998
1999
1997
1996
1996
1995
1995
1993
1993
1993
1992
1992
1991
1991
1990
1989
1988
1988
1987
1987
1987
1986
1984
1982
1980
1979
1977
1975
1975
1974
1973
1973
1972
1971
1971
1970
1969
1968
1968
1967
1966
1965
1965
1964
1963
1962
1961
1960
1959
1959
1958
1958
1957
1956
1955
1954
1955
1953
1953
1951
1950
1949
1948
1947
1945
1944
1946
1942
1941
1940
1939
1939
1934
1930
1925
2019
2020
2018
2019
2017
2016
2018
2016
2016
2016
2017
2014
2019
2016
2015
2013
2014
2011
2011
2014
2012
2019
2009
2009
2008
2009
2008
2007
2014
2007
2009
2008
2007
2006
2006
2012
2009
2005
2004
2008
2004
2004
2003
2004
2002
2002
2001
2001
2002
2000
2006
2000
2001
1999
1997
1995
1994
1993
1993
1993
1993
1990
1989
1989
1987
1986
1985
1984
1983
1980
1979
1979
1978
1976
1973
1973
1972
1972
1971
1970
1969
1968
1968
1967
1963
1962
1960
1960
1959
1956
1956
1955
1952
1951
1950
1947
1946
1946
1945
1940
1940
1938
1935
1933
1932
1922
2019
2018
2019
2016
2017
2016
2016
2017
2016
2016
2016
2016
2015
2016
2016
2015
2019
2017
2014
2013
2013
2013
2012
2014
2013
2012
2013
2019
2013
2012
2014
2015
2010
2010
2011
2013
2010
2015
2009
2008
2013
2009
2009
2020
2020
2010
2008
2008
2007
2012
2007
2007
2011
2007
2009
2009
2006
2006
2007
2008
2004
2005
2005
2005
2003
2005
2005
2003
2004
2004
2002
2003
2000
2002
2001
2000
2000
1999
2000
1999
1999
1999
2001
1997
1997
1997
1997
1996
1994
1993
1993
1993
1993
1993
1993
1993
1993
1992
1991
1991
1991
1990
1990
1989
1989
1989
1989
1988
1987
1987
1986
1986
1985
1985
1985
1984
1984
1983
1982
1982
1979
1978
1976
1975
1974
1973
1973
1973
1972
1971
1969
1967
1967
1967
1964
1964
1962
1962
1961
1960
1948
1948
1944
1943
1939
1938
1938
1935
1933
1932
1931
2018
2017
2018
2017
2017
2018
2015
2014
2014
2014
2014
2014
2015
2014
2013
2013
2012
2014
2011
2013
2012
2015
2011
2011
2014
2013
2013
2015
2010
2011
2009
2012
2012
2012
2009
2010
2008
2008
2006
2008
2010
2006
2006
2006
2014
2006
2006
2007
2006
2005
2007
2010
2006
2005
2007
2004
2004
2004
2004
2004
2003
2005
2004
2009
2003
2002
2003
2002
2001
2002
2001
2002
2001
2000
2001
2001
2000
2000
2002
1999
1999
1998
2001
1998
1997
1999
1997
1997
1998
1997
1996
1996
1996
1995
1995
1994
1994
1993
1993
1992
1992
1992
1992
1992
1992
1991
1991
1990
1988
1988
1987
1987
1987
1986
1986
1985
1985
1983
1982
1982
1982
1980
1980
1979
1978
1976
1975
1974
1974
1973
1973
1972
1971
1971
1968
1968
1967
1967
1966
1965
1964
1964
1963
1962
1960
1960
1960
1956
1955
1955
1954
1952
1951
1951
1946
1940
1933
2019
2018
2019
2017
2017
2019
2017
2019
2015
2015
2017
2017
2017
2015
2018
2016
2015
2015
2014
2016
2013
2014
2012
2011
2012
2010
2018
2010
2010
2010
2011
2010
2009
2011
2011
2009
2008
2009
2009
2007
2008
2007
2007
2009
2006
2007
2007
2006
2006
2004
2009
2006
2005
2009
2005
2004
2008
2004
2003
2004
2003
2003
2002
2004
2002
2004
2002
2000
2001
2001
2001
2001
2001
2001
2002
1999
2000
1998
1998
1998
1998
1997
1998
1996
1997
1995
1995
1995
1995
PG
1994
1993
1993
1992
1991
1991
1990
1990
1989
1989
1988
1987
1987
1984
1981
1981
1979
1979
1979
1978
1978
1977
1973
1971
1970
1967
1966
1964
1961
1956
1953
1944
1935